version: 2.1
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-npm
      - node/install-packages:
          cache-path: node_modules
          override-ci-command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    docker:
      - image: cimg/node:current
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: npm test
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: pnadalini/noce-circleci
          tag: "latest,$CIRCLE_SHA1"
      - docker/push:
          digest-path: /tmp/digest.txt
          image: pnadalini/noce-circleci
          tag: "latest,$CIRCLE_SHA1"
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  deploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install ecs-deploy
      - run:
          name: Deploy
          command: |
            ecs deploy $ECS_CLUSTER_NAME $ECS_SERVICE --image website-service geovannnylopez97/express-js:$CIRCLE_SHA1 --timeout 1200 --ignore-warnings --region $AWS_REGION
orbs:
  docker: circleci/docker@1.4.0
  node: circleci/node@3.0.0
workflows:
  version: 2
  test:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-and-push:
          requires:
            - test
      - deploy:
          requires:
            - build-and-push
